# Python a numpy

- základní knihovna pro práci s poli
- rychlá
- v polích pouze hodnota jednoho typu

In [1]:
import numpy as np


## Přemysl Oráč to ví - generování polí
---
základem numpy je pole, můžeme ho vytvořit ze seznamu

In [2]:
A = np.array([1, 2, 3]) # pole 1 x 3
print(A)

[1 2 3]


nebo seznamu seznamů

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6] ])  # pole 2 x 3
print(A)

[[1 2 3]
 [4 5 6]]


speciální pole se nám mohou hodit

In [8]:
A = np.zeros((3, 4))  # pole nul 3 x 4, pozor na zadavani pomoci dvojice! 
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


někdy se nám může hodit zadat i typ hodnot v poli

In [10]:
A = np.zeros((3, 4), dtype = int)
print(A)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [12]:
A = np.ones((2, 5))
print(A)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


repeat

In [3]:
A = np.repeat(3, 5)
print(A)

[3 3 3 3 3]


In [6]:
A = np.repeat(3, 12).reshape(3, 4) 
print(A)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


nebo

In [3]:
A = np.full((3, 4), 3)
print(A)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


## Info o poli

In [4]:
A.ndim   # rozmery

2

In [28]:
A.size   # pocet prvku

4

In [27]:
A.shape  # tvar

(2, 2)

## Konverze ze seznamu na numpy pole
---

In [5]:
l = [1, 2, 3, 4, 6]
print(type(l))

<class 'list'>


In [6]:
a = np.array(l)
print(type(a))

<class 'numpy.ndarray'>


## Rozsahy
---

In [11]:
v = np.arange(12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
v = np.arange(1, 20, 5)   # od, do, krok  
v

array([ 1,  6, 11, 16])

In [14]:
v = np.arange(0, np.pi, 0.1 )   # floatove, proc ne
v

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1])

pokud ale chceme jasný počet kroků, hodí se pro vzorkování

In [15]:
v = np.linspace(0, np.pi, 10)
v

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

na tom krásně můžeme evaluovat funkce 

In [16]:
np.sin(v)

array([0.00000000e+00, 3.42020143e-01, 6.42787610e-01, 8.66025404e-01,
       9.84807753e-01, 9.84807753e-01, 8.66025404e-01, 6.42787610e-01,
       3.42020143e-01, 1.22464680e-16])

## Základní operace
---

aritmetické operace se aplikují po koeficientech

In [19]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

b - a

array([1, 1, 1, 1])

In [20]:
10 * a

array([10, 20, 30, 40])

In [21]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 3], [4, 5]])

A * B   # pozor neni maticove nasobeni, ale po slozkach 


array([[ 2,  6],
       [12, 20]])

maticové násobení se udělá takto

In [22]:
A @ B

array([[10, 13],
       [22, 29]])

i porovnání funguje po složkách

In [23]:
A < B

array([[ True,  True],
       [ True,  True]])

## Výběry
---
proč je horní mez exkluzivní? 

word[:2]    # první dvě písmena

word[2:]    # vše kromě prvních dvou písmen

word[:i] + word[i:] = word

místa kam klademe přihrádky, když chceme rozdělit

In [33]:
A = np.array([[1, 2, 3], [3, 4, 5]])
B = A[:, 0:2]
B

array([[1, 2],
       [3, 4]])

In [35]:
B = A[1, 1:]
B

array([4, 5])

In [37]:
B = A[-1, :]
B

array([3, 4, 5])

vybírat lze i indexovým polem

In [39]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
ind = np.array([1, 1, 2, 3, 5])

a[ind]


array([2, 2, 3, 4, 6])

vybírat lze i boolovským polem

In [40]:
ind = np.array([False, True, False, True, False, False, False, True])
a[ind]

array([2, 4, 8])

a tudíž i takto pomocí logických podmínek

In [42]:
b = a[a % 2 == 0]    # vyber sude 
b

array([2, 4, 6, 8])

nastavení prvků

In [62]:
A

array([[1, 2],
       [3, 4]])

In [63]:
A[0, 0] = 50
A

array([[50,  2],
       [ 3,  4]])

In [29]:
c = np.array([2, 3, 4, 5, 6])   # posledni element pole
c[-1]

6

## Změna tvaru
---
je rozdíl mezi reshape (vrací pohled do pole) a resize (mění tvar pole)

In [17]:
A = np.arange(12)

B = A.reshape(3, 4)
print(A, "\n")
print(B, "\n")

A.resize(3, 4)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


pole můžeme slévat, horizontálně i vertikálně

In [53]:
print(np.hstack((A, B)))    # pozor na dvojici!

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [54]:
print(np.vstack((A, B))) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


transpozice

In [18]:
A.T  # nebo A.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [22]:
a = np.array([1, 2, 3]).T   # pozooor tohle nic neudělá
a = np.array([[1, 2, 3]]).T
print(a)

[[1]
 [2]
 [3]]


splácnutí - flatten (vytváří nové pole), ravel (vytváří pohled)

In [77]:
A.ravel()

array([1, 2, 3, 4])

## Kopie
---
pozor! kopie se nevytváří automaticky


In [57]:
A = np.array([[1, 2], [3, 4]])
B = A
B[0, 0] = 4
A

array([[4, 2],
       [3, 4]])

In [61]:
A = np.array([[1, 2], [3, 4]])

B = A.copy()
B[0, 0] = 4
A

array([[1, 2],
       [3, 4]])

## Množiny
---


In [32]:
d = np.array([1, 2, 3, 4, 5])
e = np.array([3, 4, 6, 7, 8])

prunik = np.intersect1d(d, e)  # union1d
print(prunik)

[3 4]


In [34]:
np.isin(5, d)

array(True)

## Basic operace
---

suma


In [64]:
a = np.arange(10)
a.sum()

45

In [70]:
A = np.array([[1, 2], [3, 4]])
A.sum()

A.sum(axis=0)   # 0 vertikalni osa, 1 vodorovna osa

array([4, 6])

minimum a maximum

In [67]:
a.min()
a.max()

9

In [68]:
A.min()

1

In [69]:
A.min(axis=0)  # jde to po osach

array([1, 2])

ostatni

In [73]:
b = np.array([3, 1, 2, 1, 5, 7, 8, 4])
np.unique(b)  # jedinecna cisla, POZOR umi vracet i indexy cisel a pocty

array([1, 2, 3, 4, 5, 7, 8])

In [74]:
np.sort(b)    # trideni

array([1, 1, 2, 3, 4, 5, 7, 8])

In [79]:
np.flip(b)  # reverze pole

array([4, 8, 7, 5, 1, 2, 1, 3])

## Cyklení skrz pole
---

In [81]:
a = np.arange(5)

for i in a:
    print(i)

0
1
2
3
4


u pole se jede primárně přes řádky

In [82]:
A = np.array([[1, 2, 3], [7, 8, 9]])
for row in A:
    print(row)

[1 2 3]
[7 8 9]


cyklus přes všechny prvky pole  (flat vrací iterátor)

In [83]:
for i in A.flat:
    print(i)

1
2
3
7
8
9


## Broadcasting
---

## Ufunkce
---
funkce pracující na polích
[odkaz dokumentace](https://numpy.org/doc/stable/reference/ufuncs.html)

In [24]:
a = np.array([1, 2, 3, 4])
np.log(a)
np.square(a)

array([ 1,  4,  9, 16])

## Hledání - indexy
---

where  (podobně funguje třeba nonzero() )

In [27]:
A = np.array([[1, 2, 3],[3, 4, 5]])
ind = np.where(A > 3)
ind

A[ind]



array([4, 5])

## Náhoda
---
nejprve specifikujeme náhodný generátor - good practice

In [4]:
rng = np.random.default_rng(12345)  # seed
rng.random()  # nahodny float 

0.22733602246716966

### integery

In [92]:
randints = rng.integers(1, 10, 5) # 5 nahodnych integeru z rozsahu 1 az 10 (ne vcetne)
randints

array([5, 7, 2, 3, 2])

### floaty

In [98]:
rng.random() # jedno cislo v [0, 1)

0.8547419043740013

In [97]:
rng.random((3, 3)) # matice nahodnych floatu 3x3, POZOR na zavorky

array([[0.1598956 , 0.34010018, 0.46519315],
       [0.26642103, 0.8157764 , 0.19329439],
       [0.12946908, 0.09166475, 0.59856801]])

### výběry

In [8]:
a = np.arange(12)
b = rng.choice(a, 4) # vyber 4 cisla s opakovanim !!!
b

array([2, 2, 2, 8])

In [10]:
c = rng.choice(a, 7, replace=False)  # vyber bez opakovani
c

array([ 7,  9,  8,  5,  1,  3, 10])

### permutace
shuffle  (mění sekvenci na místě), permutation (vrací nové pole), lze použít i na 2D pole

In [107]:
a = np.arange(12)
print(a)
rng.shuffle(a)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 2  9  7  6  8  4  0  5 10  1  3 11]


In [109]:
A = np.array([[1, 2], [3, 4], [5, 6]])
rng.shuffle(A, axis=0)
A

array([[3, 4],
       [5, 6],
       [1, 2]])

### jiné distribuce
lze použít hromadu jiných distribucí

In [112]:
rng.binomial(10, 0.5, 15) # 15x testujeme kolikrat behem 10 pokusu hazeni ferovou minci padne orel

array([6, 3, 7, 5, 5, 4, 4, 1, 4, 7, 8, 5, 5, 4, 8])